### ISSUE TITLE
Aseprite loading not working

### ISSUE THREAD

**Issue by jobe-m** [korlibs/korge-fleks-hello-world#5]
After updating the Korge-fleks-hello-world example repo the jvm build failed with following message:

    e: file:///home/jobe/korge/korge-fleks-hello-world/build/KR/KR.kt:31:57 Unresolved reference: AseSpritesAse

Why is that file `KR.kt` generated and how can this be fixed?

@soywiz Do you have an idea?

**Comment by soywiz** [comment]
@jobe-m is there a branch where I can check that error?

**Comment by jobe-m** [comment]
You can use the main branch. I pushed the changes directly there.

**Comment by soywiz** [comment]
@jobe-m circumvented the issue here: https://github.com/korlibs/korge-fleks-hello-world/commit/f898e447414ce8815e30543ca4f9008364e74351 it seems that the KR genereation fails with the .ase provided there. Looks like a bug. I guess that if for some reason there is an error in the processed input, that file should be skipped altogether.
